#include <stdio.h>
#include "sym16x16.h"

unsigned char *fontmat16x16[] =
{
space16x16, //sp
CirclePoint, //!
NULL, //" Áô¿Õ
Single_0, //#
Single_1, //$
Single_2, //% 
Single_3, //& 
Single_4, //' 
Single_0_G, //( 
Single_1_G, //) 
Single_2_G, //* 
Single_3_G, //+ 
Single_4_G, //, 
Single_0_C, //- 
Single_1_C, //. 
Single_2_C, /// 
Single_3_C, //0 
Single_4_C, //1 
Single_0_L, //2 
Single_1_L, //3 
Single_2_L, //4 
Single_3_L, //5 
Single_4_L, //6 
BatteryEnd_0, //7 
BatteryEnd_1, //8 
BatteryEnd_2, //9 
BatteryEnd_3, //: 
BatteryHead_3, //; 
BatteryHead_4, //< 
BatteryHead_5, //= 
BatteryHead_0, //> 
Comm_G_Nologon, //? 
Comm_G_Idle, //@
Comm_G_Busy, //A
Comm_C_Nologon, //B
Comm_C_Idle, //C
Comm_C_Busy, //D
Comm_L_Nologon, //E
Comm_L_Idle, //F
Comm_L_Busy, //G
Comm__Idle, //H 
Comm__Busy, //I 
LittleBattery_0, //J 
LittleBattery_1, //K 
LittleBattery_2, //L 
LittleBattery_3, //M 
LittleBattery_4, //N 
LittleBattery_5, //O 
Directin_up_Fill_dn_Fill, //P
Directin_up_Fill_dn_Empty, //Q
Directin_up_Empty_dn_Fill, //R
Directin_up_Empty_dn_Empty, //S
Directin_up_dn, //T
Directin_up, //U
Directin_dn, //V
Ethernet_Status_up, //W
Ethernet_Status_dn, //X
Com_Status_up, //Y 
Com_Status_dn, //Z
Usb_Disk_Flag, //[
NULL, //\ Áô¿Õ
Gprs_Status_up, //] 
Gprs_Status_dn, //^ 
ZB_Status_up, //_ 
ZB_Status_dn, //'
RS485I_Status_up, //a  
RS485I_Status_dn, //b 
RS485II_Status_up, //c 
RS485II_Status_dn, //d
RS485III_Status_up, //e
RS485III_Status_dn, //f
Usb_Status_up, //g
Usb_Status_dn, //h
Store_Status_up, //i
Store_Status_dn, //j
Single_0_Antenna, //k
Single_1_Antenna, //l
Single_2_Antenna, //m
Single_3_Antenna, //n
Single_4_Antenna, //o
Program_key_Lock_open, //p
Program_key_Lock_close, //q
Common_3G_nologon, //r
Common_3G_idle, //s
Common_3G_busy, //t
Common_4G_nologon, //u
Common_4G_idle, //v
Common_4G_busy, //w
NULL, //x
NULL, //y
NULL, //z
NULL, //{
NULL, //|
NULL, //}
NULL, //~
};
