#include <stdio.h>
#include "sym8x16.h"

unsigned char *fontmat8x16[] =
{
space8x16, //sp
antenna8x16, //!  //ÌìÏß
NULL, //" Áô¿Õ
NULL, //#
up_arrow, //$ 
down_arrow, //% 
left_yan_0, //& 
left_yan_1, //` 
left_yan_2, //( 
left_yan_3, //) 
left_yan_4, //* 
left_yan_5, //+ 
left_yan_6, //, 
left_yan_7, //- 
left_yan_8, //. 
left_yan_9, /// 
right_yan_0, //0 
right_yan_1, //1 
right_yan_2, //2 
right_yan_3, //3 
right_yan_4, //4 
right_yan_5, //5 
right_yan_6, //6 
right_yan_7, //7 
right_yan_8, //8 
right_yan_9, //9 
left_yin_0, //: 
left_yin_1, //; 
left_yin_2, //< 
left_yin_3, //= 
left_yin_4, //> 
left_yin_5, //? 
left_yin_6, //@
left_yin_7, //A
left_yin_8, //B
left_yin_9, //C
right_yin_0, //D
right_yin_1, //E
right_yin_2, //F
right_yin_3, //G
right_yin_4, //H 
right_yin_5, //I 
right_yin_6, //J 
right_yin_7, //K 
right_yin_8, //L 
right_yin_9, //M 
middle_yan_0, //N 
middle_yan_1, //O 
middle_yan_2, //P
middle_yan_3, //Q
middle_yan_4, //R
middle_yan_5, //S
middle_yan_6, //T
middle_yan_7, //U
middle_yan_8, //V
middle_yan_9, //W
NULL, //X
NULL, //Y 
NULL, //Z
NULL, //[
NULL, //\ Áô¿Õ
NULL, //] 
NULL, //^ 
NULL, //_ 
NULL, //'
middle_yin_0, //a  
middle_yin_1, //b 
middle_yin_2, //c 
middle_yin_3, //d
middle_yin_4, //e
middle_yin_5, //f
middle_yin_6, //g
middle_yin_7, //h
middle_yin_8, //i
middle_yin_9, //j
NULL, //k
NULL, //l
NULL, //m
NULL, //n
NULL, //o
NULL, //p
NULL, //q
NULL, //r
NULL, //s
NULL, //t
NULL, //u
NULL, //v
NULL, //w
NULL, //x
NULL, //y
NULL, //z
NULL, //{
NULL, //|
NULL, //}
NULL, //~
};
